# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IoT DevKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IoT DevKit
  pod 'AWSIoT'
#  pod 'ButtonProgressBar-iOS'
#  pod 'Font-Awesome-Swift'

  target 'IoT DevKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IoT DevKitUITests' do
    # Pods for testing
  end

end
